spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./credit_db
    username: user
    password: 1234

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
